=== QuentinDevJava/Martel-Quentin-tester-Java/src/assembly/assembly.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="assembly">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:string" />
				<xs:element name="formats">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="format" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="includeBaseDirectory" type="xs:string" />
				<xs:element name="dependencySets">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dependencySet">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="unpack" type="xs:string" />
										<xs:element name="scope" type="xs:string" />
										<xs:element name="useProjectArtifact" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="fileSets">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="fileSet">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="directory" type="xs:string" />
										<xs:element name="outputDirectory" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== QuentinDevJava/Martel-Quentin-tester-Java/src/assembly/assembly.xml
<assembly xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="assembly.xsd">
  <id>executable-jar-with-dependencies</id>
  <formats>
    <format>jar</format>
  </formats>
  <includeBaseDirectory>false</includeBaseDirectory>
  <dependencySets>
    <dependencySet>
      <!-- unpack les dÃ©pendances avant de les inclures dans le jar final de l'application -->
      <unpack>true</unpack>
      <scope>runtime</scope>
      <useProjectArtifact>false</useProjectArtifact>
    </dependencySet>
  </dependencySets>
  <fileSets>
    <fileSet>
      <directory>${project.build.outputDirectory}</directory>
      <outputDirectory></outputDirectory>
    </fileSet>
  </fileSets>
</assembly>
